### ISSUE TITLE
Get-ADHealthConfig is not recognized as the name of a cmdlet, function, script file, or operable program

### ISSUE THREAD

**Issue by benemanuel** [compwiz32/PSADHealth#59]
I can't find it anywhere.

**Comment by mattfippard** [comment]
The command is Get-ADConfig, but the documentation is either wrong or the command should actually be Get-ADHealthConfig (which would make more sense)

**Comment by steviecoaster** [comment]
It would be a breaking change to _rename_ the cmdlet. However, adding an alias would be trivial, and I believe the best option so we don't need to update a large swath of the codebase.
